Fix : ValueError when input is str
When we input selection as 'str' instead of 'int', exception occurs at line 65 -

Traceback (most recent call last):
  File "/home/user/Tool/PhishMailer/PhishMailer.py", line 183, in <module>
    mainMenu()
  File "/home/user/Tool/PhishMailer/PhishMailer.py", line 65, in mainMenu
    mailPick = int(input(green + "root@phishmailer:~ " + white))
ValueError: invalid literal for int() with base 10: 'er'